version: '3'
services:
    tomcat:
      image: tomcat:9-jdk8-openjdk
      container_name: bookingplant
      ports:
        - "8080:8080"
      volumes:
        - ./target/Booking-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/Booking.war